name: "dnsX"

on:
  workflow_dispatch:
    inputs:
      input_filename:
        default: "input/dnsx-input"
        description: "File name with all the subdomains to scan"
      output_filename:
        default: "output/dnsx-output"
        description: "Where to put the results"
      resolvers_filename:
        default: "config/resolvers.txt"
        description: "File name with all the DNS resolvers to use"
      extra_flags:
        default: ""
        description: "Extra flags to pass to dnsx"
  # schedule: [{"cron": "0 0 * * *"}]

jobs:
  
  split:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: 💥 dnsx - DNS Resolver
        uses: projectdiscovery/dnsx-action@main
        with:
          list: ${{ github.event.inputs.input_filename }}
          output: ${{ github.event.inputs.output_filename }}
          resolver: ${{ github.event.inputs.resolvers_filename }}
          flags: ${{ github.event.inputs.extra_flags }}

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: output/*
