name: "subfinder"

on:
  workflow_dispatch:
    inputs:
      input_filename:
        default: "input/subfinder-input"
        description: "File name with all the apex domains to scan"
      output_filename:
        default: "output/subfinder-output"
        description: "Where to put the results"
      config_folder:
        default: "config/subfinder/general/config.yaml"
        description: "Folder containing subfinder configurations files"
  # schedule: [{"cron": "0 0 * * *"}]

jobs:
  subfinder:
    runs-on: kali
    steps:
      - uses: actions/checkout@v4

      - name: SubFinder - DNS Enumeration
        uses: projectdiscovery/subfinder-action@main
        with:
          list: ${{ github.event.inputs.input_filename }}
          output: ${{ github.event.inputs.output_filename }}
          config: ${{ github.event.inputs.config_folder }}

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: output/*
