name: "subfinder"

on:
  workflow_dispatch:
    inputs:
      list:
        default: "input/subfinder-input"
        description: "List of domains to run subdomain enumeration"
      config:
        default: "config/subfinder/general/config.yaml"
        description: "Config file to use with subdomain enumeration"
      output:
        default: "output/subfinder-output"
        description: "File to save output result"
      json:
        default: "false"
        description: "Write results in JSON format"
      flags:
        default: ""
        description: "Additional subfinder CLI flags to use"
      active:
        default: "false"
        description: "Filter subdomains with no DNS records"
  issue_comment:
    types: [created]

jobs:
  subfinder:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: 💥 subfinder - DNS Enumeration
        if: github.event_name == 'workflow_dispatch'
        uses: projectdiscovery/subfinder-action@main
        with:
          list: ${{ github.event.inputs.list }}
          config: ${{ github.event.inputs.config }}
          output: ${{ github.event.inputs.output }}
          json: ${{ github.event.inputs.json }}
          flags: ${{ github.event.inputs.flags }}
          active: ${{ github.event.inputs.active }}

      - uses: EndBug/add-and-commit@v9
        if: github.event_name == 'workflow_dispatch'
        with:
          default_author: github_actions
          add: ${{ github.event.inputs.output }}
      
      - name: Parse input from issue_comment
        id: parse_issue_comment
        if: github.event_name == 'issue_comment' && fromJSON(github.event.comment.body).tool == 'subfinder'
        run: |
          inputs=${{ fromJSON(github.event.comment.body) }}
          echo "domain=${inputs.domain}" >> $GITHUB_OUTPUT
          echo "config=${inputs.config}" >> $GITHUB_OUTPUT
          echo "flags=${inputs.flags}" >> $GITHUB_OUTPUT
          echo "active=${inputs.active}" >> $GITHUB_OUTPUT

      - name: 💥 subfinder - DNS Enumeration
        if: github.event_name == 'issue_comment' && fromJSON(github.event.comment.body).tool == 'subfinder'
        uses: projectdiscovery/subfinder-action@main
        with:
          domain: ${{ steps.parse_issue_comment.outputs.domain }}
          config: ${{ steps.parse_issue_comment.outputs.config }}
          flags: ${{ steps.parse_issue_comment.outputs.flags }}
          active: ${{ steps.parse_issue_comment.outputs.active }}

      
      - name: Add comment with subfinder log
        if: github.event_name == 'issue_comment' && fromJSON(github.event.comment.body).tool == 'subfinder'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('subfinder.log', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              in_reply_to: github.context.payload.comment.id,
              body: '```\n' + body + '\n```',
            });