name: "subfinder"

on:
  workflow_dispatch:
    inputs:
      input_filename:
        default: "input/subfinder-input"
        description: "File name with all the apex domains to scan"
      output_filename:
        default: "output/subfinder-output"
        description: "Where to put the results"
      config_folder:
        default: "config/subfinder/general/config.yaml"
        description: "Folder containing subfinder configurations files"
  # schedule: [{"cron": "0 0 * * *"}]

jobs:
  subfinder:
    permissions:
      contents: write
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: SubFinder - DNS Enumeration
        uses: projectdiscovery/subfinder-action@main
        with:
          list: ${{ github.event.inputs.input_filename }}
          output: ${{ github.event.inputs.output_filename }}
          config: ${{ github.event.inputs.config_folder }}
          json: true

      - name: Save Results
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5

      - name: "Run if changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: echo "Changes!"

      - name: "Run if no changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'false'
        run: echo "No Changes!"
