name: "subfinder"

on:
  workflow_dispatch:
    inputs:
      input_filename:
        default: "input/subfinder-input"
        description: "File name with all the apex domains to scan"
      output_filename:
        default: "output/subfinder-output"
        description: "Where to put the results"
      config_folder:
        default: "config/subfinder/general/config.yaml"
        description: "Folder containing subfinder configurations files"
  # schedule: [{"cron": "0 0 * * *"}]

jobs:
  subfinder:
    permissions:
      contents: write
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: SubFinder - DNS Enumeration
        uses: projectdiscovery/subfinder-action@main
        with:
          list: ${{ github.event.inputs.input_filename }}
          output: workspace/subfinder-output
          config: ${{ github.event.inputs.config_folder }}

      - name: Save Results
        run: |
          go install -v github.com/tomnomnom/anew@latest
          sudo apt update && sudo apt install git -y
          cat workspace/subfinder-output | anew ${{ github.event.inputs.output_filename }} > news/subfinder-news

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
