name: Update Nuclei Templates

on:
  schedule: [{"cron": "0 0 * * 1"}]
  workflow_dispatch:

jobs:
  update-nuclei-templates:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch_to_update: [Grammarly, Vimeo, main]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ matrix.branch_to_update }}

      - name: Update templates
        run: |
          git config --global user.email "18237644+amocsub@users.noreply.github.com"
          git config --global user.name "amocsub"
          git submodule update --recursive --remote
          git add config/nuclei/nuclei-templates
          git commit -m "Update Nuclei templates" || echo "No changes to commit"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin ${{ matrix.branch_to_update }}
