name: Update Nuclei Templates

on:
  schedule: [{"cron": "0 0 * * 1"}]

jobs:
  update-nuclei-templates:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Update templates
        run: |
          git config --global user.email "18237644+amocsub@users.noreply.github.com"
          git config --global user.name "amocsub"
          git submodule update --recursive --remote
          git add config/nuclei/nuclei-templates
          git commit -m "Update Nuclei templates" || echo "No changes to commit"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin ${{ github.ref }}
