name: Update Nuclei Templates
on:
  workflow_dispatch:
  # schedule: [{"cron": "0 0 * * *"}]

jobs:
  update-nuclei-templates:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Update templates
        run: |
          git submodule update --recursive --remote

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: config/nuclei/nuclei-templates/*
